export const CATEGORIES = [
  {
    id: 'wedding',
    name: 'Wedding',
    icon: '💒',
    gradient: ['#FFE2E6', '#FFC2CE'],
    subcategories: ['Traditional', 'Modern', 'Destination', 'Royal'],
  },
  {
    id: 'birthday',
    name: 'Birthday',
    icon: '🎂',
    gradient: ['#E3F2FD', '#BBDEFB'],
    subcategories: ['Kids', 'Adults', 'Surprise', 'Theme'],
  },
  {
    id: 'babyshower',
    name: 'Baby Shower',
    icon: '👶',
    gradient: ['#FFF3E0', '#FFE0B2'],
    subcategories: ['Gender Reveal', 'Traditional', 'Modern'],
  },
  {
    id: 'corporate',
    name: 'Corporate',
    icon: '🏢',
    gradient: ['#E8F5E9', '#C8E6C9'],
    subcategories: ['Conference', 'Award Night', 'Product Launch'],
  },
  {
    id: 'festival',
    name: 'Festival',
    icon: '✨',
    gradient: ['#F3E5F5', '#E1BEE7'],
    subcategories: ['Diwali', 'Christmas', 'New Year'],
  },
  {
    id: 'party',
    name: 'Party',
    icon: '🎉',
    gradient: ['#FFEBEE', '#FFCDD2'],
    subcategories: ['House Party', 'Pool Party', 'Cocktail'],
  },
];

export const MOCK_PRODUCTS = [
  {
    id: '1',
    title: 'Elegant Wedding Setup',
    price: 149999,
    description: 'Luxurious wedding decoration package with floral arrangements, lighting, and seating for 200 guests.',
    rating: 4.8,
    reviews: 124,
    modelUrl: 'https://example.com/models/wedding-setup.glb',
    images: [
      'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop',
      'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop',
      'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop',
    ],
    category: 'wedding',
    subcategory: 'Modern',
    features: [
      'Complete venue decoration',
      'Fresh flower arrangements',
      'LED lighting setup',
      'Premium seating decor',
      'Entry arch and stage backdrop',
    ],
    materials: [
      'Fresh flowers and greens',
      'Premium fabric drapes',
      'LED light strings',
      'Designer furniture',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events',
      rating: 4.8,
      reviews: 89,
      responseTime: '< 1 hour',
      completedEvents: 200,
    },
    customization: {
      colors: ['Pink & Gold', 'White & Silver', 'Royal Blue', 'Custom'],
      addons: [
        { id: 'a1', name: 'Photo Booth', price: 9999 },
        { id: 'a2', name: 'LED Dance Floor', price: 24999 },
        { id: 'a3', name: 'Extra Flower Wall', price: 14999 },
      ],
    },
  },
  {
    id: '2',
    title: 'Birthday Party Decor',
    price: 29999,
    description: 'Colorful and fun birthday party decoration set perfect for memorable celebrations.',
    rating: 4.9,
    reviews: 86,
    modelUrl: 'https://example.com/models/birthday-setup.glb',
    images: [
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop',
      'https://images.unsplash.com/photo-1464047736614-af63643285bf?auto=format&fit=crop',
      'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop',
    ],
    category: 'birthday',
    subcategory: 'Theme',
    features: [
      'Themed party setup',
      'Balloon decorations',
      'Banner and props',
      'Table settings',
      'Cake table decor',
    ],
    materials: [
      'Premium balloons',
      'Theme-based props',
      'Party banners',
      'Table accessories',
    ],
    vendor: {
      id: 'v2',
      name: 'Party Perfect',
      rating: 4.9,
      reviews: 56,
      responseTime: '< 2 hours',
      completedEvents: 150,
    },
    customization: {
      colors: ['Rainbow', 'Gold & Black', 'Pink & Purple', 'Custom'],
      addons: [
        { id: 'a4', name: 'Balloon Arch', price: 4999 },
        { id: 'a5', name: 'Candy Station', price: 7999 },
        { id: 'a6', name: 'Party Games Setup', price: 5999 },
      ],
    },
  },
  {
    id: '3',
    title: 'Corporate Event Setup',
    price: 99999,
    description: 'Professional corporate event decoration with modern and minimalist design.',
    rating: 4.7,
    reviews: 92,
    modelUrl: 'https://example.com/models/corporate-setup.glb',
    images: [
      'https://images.unsplash.com/photo-1505236858219-8359eb29e329?auto=format&fit=crop',
      'https://images.unsplash.com/photo-1469533778471-92a68acc3633?auto=format&fit=crop',
      'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop',
    ],
    category: 'corporate',
    subcategory: 'Conference',
    features: [
      'Stage setup with branding',
      'Professional lighting',
      'Seating arrangement',
      'Registration desk',
      'Breakout area decor',
    ],
    materials: [
      'Stage backdrop',
      'LED screens',
      'Premium furniture',
      'Branding materials',
    ],
    vendor: {
      id: 'v3',
      name: 'Business Events Pro',
      rating: 4.7,
      reviews: 72,
      responseTime: '< 3 hours',
      completedEvents: 180,
    },
    customization: {
      colors: ['Corporate Blue', 'Modern Black', 'White & Gold', 'Custom'],
      addons: [
        { id: 'a7', name: 'LED Wall', price: 29999 },
        { id: 'a8', name: 'Sound System', price: 19999 },
        { id: 'a9', name: 'VIP Lounge', price: 24999 },
      ],
    },
  },
];