// Centralized product data used across the app
// 3D models: using a single public sample model for all products for now.
// This keeps the 3D preview working without any hosting setup.
// Later, replace MODEL_BASE_URL or individual modelUrl values with your own GLB URLs.
const MODEL_BASE_URL = 'https://modelviewer.dev/shared-assets/models/';

export const DECOR_PRODUCTS = [
  // ========================================
  // HALDI CATEGORY
  // Using YOUR uploaded images from ImgBB
  // ========================================
  {
    id: 'haldi_001',
    title: 'Traditional Haldi Ceremony Setup',
    price: 19999,
    originalPrice: 28999,
    rating: 4.8,
    reviews: 156,
    organizer: 'Joyful Celebrations',
    image: 'https://i.ibb.co/KpzBGHMM/H1.jpg',
    images: [
      'https://i.ibb.co/KpzBGHMM/H1.jpg',
      'https://i.ibb.co/WvTW33Nq/H2.jpg',
      'https://i.ibb.co/tPYchbXf/H3.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Haldi',
    description: 'Beautiful traditional Haldi ceremony decoration with vibrant yellow and orange marigold arrangements. Perfect for creating authentic and joyful pre-wedding celebrations.',
    features: [
      'Vibrant marigold flower decorations',
      'Traditional seating arrangement',
      'Colorful drapes and fabrics',
      'Photo booth setup',
      'Complete ceremony decor package',
    ],
    vendor: {
      id: 'v2',
      name: 'Joyful Celebrations',
      rating: 4.8,
      totalOrders: 320,
    },
    inStock: true,
  },
  {
    id: 'haldi_002',
    title: 'Elegant Haldi Garden Decor',
    price: 24999,
    originalPrice: 35999,
    rating: 4.9,
    reviews: 189,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/whSfs9Yt/H4.jpg',
    images: [
      'https://i.ibb.co/whSfs9Yt/H4.jpg',
      'https://i.ibb.co/Q7MsGZQ9/H5.jpg',
      'https://i.ibb.co/5WD38v9x/H6.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Haldi',
    description: 'Elegant garden-themed Haldi decoration with fresh flowers and natural elements. Ideal for outdoor ceremonies with sophisticated yellow and white color palette.',
    features: [
      'Fresh flower arrangements',
      'Natural garden aesthetics',
      'Elegant seating decor',
      'Decorative umbrellas and canopies',
      'Professional styling team',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'haldi_003',
    title: 'Royal Haldi Function Package',
    price: 27999,
    originalPrice: 39999,
    rating: 4.7,
    reviews: 203,
    organizer: 'Celebration Masters',
    image: 'https://i.ibb.co/bjQY7XWY/H7.jpg',
    images: [
      'https://i.ibb.co/bjQY7XWY/H7.jpg',
      'https://i.ibb.co/mFTgQHkv/H8.jpg',
      'https://i.ibb.co/35D41rtB/H9.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Haldi',
    description: 'Royal Haldi function decoration with luxurious setup and premium floral work. Features traditional elements combined with modern elegance for memorable celebrations.',
    features: [
      'Premium floral arrangements',
      'Luxury fabric draping',
      'Traditional decor elements',
      'Customizable theme colors',
      'Complete function coverage',
    ],
    vendor: {
      id: 'v3',
      name: 'Celebration Masters',
      rating: 4.7,
      totalOrders: 280,
    },
    inStock: true,
  },
  {
    id: 'haldi_004',
    title: 'Vibrant Haldi Celebration Setup',
    price: 22999,
    originalPrice: 32999,
    rating: 4.8,
    reviews: 175,
    organizer: 'Joyful Celebrations',
    image: 'https://i.ibb.co/9mt7m4cq/H10.jpg',
    images: [
      'https://i.ibb.co/9mt7m4cq/H10.jpg',
      'https://i.ibb.co/qYmZBHDX/H11.jpg',
      'https://i.ibb.co/8gdR8snY/H12.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Haldi',
    description: 'Vibrant and colorful Haldi celebration setup with energetic decor elements. Perfect for creating lively atmosphere with traditional marigold and modern accents.',
    features: [
      'Energetic color combinations',
      'Traditional marigold decor',
      'Modern accent elements',
      'Fun photo opportunities',
      'Inclusive decoration package',
    ],
    vendor: {
      id: 'v2',
      name: 'Joyful Celebrations',
      rating: 4.8,
      totalOrders: 320,
    },
    inStock: true,
  },
  {
    id: 'haldi_005',
    title: 'Premium Haldi Ceremony Decor',
    price: 29999,
    originalPrice: 42999,
    rating: 4.9,
    reviews: 221,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/JwzT5y7R/H13.jpg',
    images: [
      'https://i.ibb.co/JwzT5y7R/H13.jpg',
      'https://i.ibb.co/JFCc5w6L/H14.jpg',
      'https://i.ibb.co/j9Jbtk84/H15.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Haldi',
    description: 'Premium Haldi ceremony decoration with exquisite floral work and elegant setup. Combines traditional elements with contemporary design for unforgettable celebrations.',
    features: [
      'Exquisite floral arrangements',
      'Premium seating and draping',
      'Professional lighting setup',
      'Customizable decor themes',
      'Complete ceremony transformation',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'haldi_006',
    title: 'Grand Haldi Function Package',
    price: 32999,
    originalPrice: 46999,
    rating: 4.8,
    reviews: 198,
    organizer: 'Celebration Masters',
    image: 'https://i.ibb.co/1JMkVmcC/H16.jpg',
    images: [
      'https://i.ibb.co/1JMkVmcC/H16.jpg',
      'https://i.ibb.co/spV9MmVB/H18.jpg',
      'https://i.ibb.co/B24NbTt5/H19.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Haldi',
    description: 'Grand Haldi function package with complete venue decoration and premium services. Ultimate choice for large-scale celebrations featuring luxury elements and professional installation.',
    features: [
      'Complete venue transformation',
      'Grand floral installations',
      'Premium fabric and lighting',
      'Multiple seating areas',
      'Full-service decoration team',
    ],
    vendor: {
      id: 'v3',
      name: 'Celebration Masters',
      rating: 4.7,
      totalOrders: 280,
    },
    inStock: true,
  },

  // ========================================
  // MEHENDI CATEGORY
  // Using YOUR uploaded images from ImgBB
  // ========================================
  {
    id: 'mehendi_001',
    title: 'Traditional Mehendi Ceremony Setup',
    price: 21999,
    originalPrice: 31999,
    rating: 4.9,
    reviews: 267,
    organizer: 'Joyful Celebrations',
    image: 'https://i.ibb.co/kVxt7wZM/M1.jpg',
    images: [
      'https://i.ibb.co/kVxt7wZM/M1.jpg',
      'https://i.ibb.co/6cb93fDy/M2.jpg',
      'https://i.ibb.co/5gcKP0bh/M3.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Mehendi',
    description: 'Beautiful traditional Mehendi ceremony decoration with vibrant colors and comfortable seating. Perfect for creating memorable pre-wedding celebrations with authentic decor elements.',
    features: [
      'Colorful fabric draping',
      'Comfortable seating arrangements',
      'Traditional decor elements',
      'Photo-worthy backdrops',
      'Complete ceremony package',
    ],
    vendor: {
      id: 'v2',
      name: 'Joyful Celebrations',
      rating: 4.8,
      totalOrders: 320,
    },
    inStock: true,
  },
  {
    id: 'mehendi_002',
    title: 'Elegant Mehendi Garden Decor',
    price: 25999,
    originalPrice: 36999,
    rating: 4.8,
    reviews: 294,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/ptkPYGn/M4.jpg',
    images: [
      'https://i.ibb.co/ptkPYGn/M4.jpg',
      'https://i.ibb.co/xK7DHmC9/M5.jpg',
      'https://i.ibb.co/9m6N4vHW/M6.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Mehendi',
    description: 'Elegant garden-themed Mehendi decoration with fresh flowers and natural elements. Ideal for outdoor ceremonies with sophisticated color combinations and modern aesthetics.',
    features: [
      'Fresh flower arrangements',
      'Garden-themed setup',
      'Elegant seating decor',
      'Natural aesthetic elements',
      'Professional styling services',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'mehendi_003',
    title: 'Royal Mehendi Function Package',
    price: 28999,
    originalPrice: 41999,
    rating: 4.9,
    reviews: 312,
    organizer: 'Celebration Masters',
    image: 'https://i.ibb.co/mV4j3h3r/M7.jpg',
    images: [
      'https://i.ibb.co/mV4j3h3r/M7.jpg',
      'https://i.ibb.co/zHVMkkKz/M8.jpg',
      'https://i.ibb.co/ZzLhkWNn/M9.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Mehendi',
    description: 'Royal Mehendi function decoration with luxurious setup and premium design elements. Features traditional motifs combined with contemporary elegance for unforgettable celebrations.',
    features: [
      'Premium decor elements',
      'Luxury fabric arrangements',
      'Traditional design motifs',
      'Customizable color schemes',
      'Complete function coverage',
    ],
    vendor: {
      id: 'v3',
      name: 'Celebration Masters',
      rating: 4.7,
      totalOrders: 280,
    },
    inStock: true,
  },
  {
    id: 'mehendi_004',
    title: 'Vibrant Mehendi Celebration Setup',
    price: 23999,
    originalPrice: 34999,
    rating: 4.8,
    reviews: 245,
    organizer: 'Joyful Celebrations',
    image: 'https://i.ibb.co/zH4fVsgZ/M10.jpg',
    images: [
      'https://i.ibb.co/zH4fVsgZ/M10.jpg',
      'https://i.ibb.co/QvJFqsgn/M11.jpg',
      'https://i.ibb.co/mrXXkmVV/M12.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Mehendi',
    description: 'Vibrant and energetic Mehendi celebration setup with colorful decor elements. Perfect for creating lively atmosphere with mix of traditional and modern design touches.',
    features: [
      'Vibrant color combinations',
      'Energetic decor elements',
      'Mix of traditional and modern',
      'Fun photo opportunities',
      'Inclusive decoration package',
    ],
    vendor: {
      id: 'v2',
      name: 'Joyful Celebrations',
      rating: 4.8,
      totalOrders: 320,
    },
    inStock: true,
  },
  {
    id: 'mehendi_005',
    title: 'Premium Mehendi Ceremony Decor',
    price: 31999,
    originalPrice: 45999,
    rating: 4.9,
    reviews: 328,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/9DJFRxs/M13.jpg',
    images: [
      'https://i.ibb.co/9DJFRxs/M13.jpg',
      'https://i.ibb.co/JwYYymCb/M14.jpg',
      'https://i.ibb.co/JWxBJfzX/M15.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Mehendi',
    description: 'Premium Mehendi ceremony decoration with exquisite design work and elegant setup. Combines cultural authenticity with contemporary styling for truly memorable celebrations.',
    features: [
      'Exquisite design elements',
      'Premium seating and draping',
      'Professional lighting setup',
      'Customizable decor themes',
      'Complete ceremony transformation',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'mehendi_006',
    title: 'Grand Mehendi Function Package',
    price: 34999,
    originalPrice: 49999,
    rating: 4.9,
    reviews: 356,
    organizer: 'Celebration Masters',
    image: 'https://i.ibb.co/LXNwX7fR/M16.jpg',
    images: [
      'https://i.ibb.co/LXNwX7fR/M16.jpg',
      'https://i.ibb.co/5hCddKSH/M17.jpg',
      'https://i.ibb.co/kVxt7wZM/M1.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Mehendi',
    description: 'Grand Mehendi function package with complete venue decoration and premium services. Ultimate choice for large-scale celebrations featuring luxury elements and professional installation team.',
    features: [
      'Complete venue transformation',
      'Grand design installations',
      'Premium fabric and lighting',
      'Multiple seating and activity areas',
      'Full-service decoration team',
    ],
    vendor: {
      id: 'v3',
      name: 'Celebration Masters',
      rating: 4.7,
      totalOrders: 280,
    },
    inStock: true,
  },

  // ========================================
  // SANGEET CATEGORY
  // Using YOUR uploaded images from ImgBB
  // ========================================
  {
    id: 'sangeet_001',
    title: 'Traditional Sangeet Night Setup',
    price: 24999,
    originalPrice: 35999,
    rating: 4.9,
    reviews: 289,
    organizer: 'Joyful Celebrations',
    image: 'https://i.ibb.co/TBqg6gCM/S1.jpg',
    images: [
      'https://i.ibb.co/TBqg6gCM/S1.jpg',
      'https://i.ibb.co/ymYs9RGS/S2.jpg',
      'https://i.ibb.co/N21nmLM3/S3.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Sangeet',
    description: 'Beautiful traditional Sangeet night decoration with vibrant colors and elegant setup. Perfect for creating energetic and memorable pre-wedding musical celebrations.',
    features: [
      'Vibrant stage decoration',
      'Comfortable seating arrangements',
      'Colorful lighting setup',
      'Musical performance area',
      'Complete event decor package',
    ],
    vendor: {
      id: 'v2',
      name: 'Joyful Celebrations',
      rating: 4.8,
      totalOrders: 320,
    },
    inStock: true,
  },
  {
    id: 'sangeet_002',
    title: 'Elegant Sangeet Dance Floor Setup',
    price: 27999,
    originalPrice: 39999,
    rating: 4.8,
    reviews: 312,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/N21nmLM3/S3.jpg',
    images: [
      'https://i.ibb.co/N21nmLM3/S3.jpg',
      'https://i.ibb.co/39DSFQHS/S4.jpg',
      'https://i.ibb.co/Gv5frvbY/S5.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Sangeet',
    description: 'Elegant Sangeet dance floor decoration with professional lighting and premium setup. Ideal for energetic dance performances with sophisticated ambiance and modern aesthetics.',
    features: [
      'Professional dance floor setup',
      'Premium stage lighting',
      'Elegant backdrop design',
      'Sound and light integration',
      'Performance-ready layout',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'sangeet_003',
    title: 'Royal Sangeet Celebration Package',
    price: 31999,
    originalPrice: 45999,
    rating: 4.9,
    reviews: 345,
    organizer: 'Celebration Masters',
    image: 'https://i.ibb.co/Gv5frvbY/S5.jpg',
    images: [
      'https://i.ibb.co/Gv5frvbY/S5.jpg',
      'https://i.ibb.co/1GBpsCWV/S6.jpg',
      'https://i.ibb.co/tTLqr0Bf/S7.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Sangeet',
    description: 'Royal Sangeet celebration package with luxurious setup and grand decor elements. Features premium stage design with traditional and contemporary fusion for unforgettable nights.',
    features: [
      'Grand stage installation',
      'Luxury fabric draping',
      'Premium lighting effects',
      'Multiple performance zones',
      'Complete venue transformation',
    ],
    vendor: {
      id: 'v3',
      name: 'Celebration Masters',
      rating: 4.7,
      totalOrders: 280,
    },
    inStock: true,
  },
  {
    id: 'sangeet_004',
    title: 'Vibrant Sangeet Musical Night',
    price: 26999,
    originalPrice: 38999,
    rating: 4.8,
    reviews: 276,
    organizer: 'Joyful Celebrations',
    image: 'https://i.ibb.co/tTLqr0Bf/S7.jpg',
    images: [
      'https://i.ibb.co/tTLqr0Bf/S7.jpg',
      'https://i.ibb.co/tTCN9xLd/S8.jpg',
      'https://i.ibb.co/TBqg6gCM/S1.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Sangeet',
    description: 'Vibrant Sangeet musical night decoration with energetic colors and dynamic setup. Perfect for creating lively atmosphere with excellent acoustics and visual appeal.',
    features: [
      'Energetic color scheme',
      'Optimized acoustics setup',
      'Dynamic lighting arrangements',
      'Musical instrument staging',
      'Entertainment-focused design',
    ],
    vendor: {
      id: 'v2',
      name: 'Joyful Celebrations',
      rating: 4.8,
      totalOrders: 320,
    },
    inStock: true,
  },
  {
    id: 'sangeet_005',
    title: 'Premium Sangeet Function Decor',
    price: 29999,
    originalPrice: 42999,
    rating: 4.9,
    reviews: 298,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/ymYs9RGS/S2.jpg',
    images: [
      'https://i.ibb.co/ymYs9RGS/S2.jpg',
      'https://i.ibb.co/Gv5frvbY/S5.jpg',
      'https://i.ibb.co/tTCN9xLd/S8.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Sangeet',
    description: 'Premium Sangeet function decoration with exquisite design and elegant execution. Combines traditional celebration elements with modern party aesthetics for memorable events.',
    features: [
      'Exquisite stage design',
      'Premium seating and draping',
      'Professional lighting and sound',
      'Customizable theme elements',
      'Complete function setup',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'sangeet_006',
    title: 'Grand Sangeet Night Package',
    price: 34999,
    originalPrice: 49999,
    rating: 4.9,
    reviews: 367,
    organizer: 'Celebration Masters',
    image: 'https://i.ibb.co/1GBpsCWV/S6.jpg',
    images: [
      'https://i.ibb.co/1GBpsCWV/S6.jpg',
      'https://i.ibb.co/tTLqr0Bf/S7.jpg',
      'https://i.ibb.co/tTCN9xLd/S8.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Sangeet',
    description: 'Grand Sangeet night package with complete venue decoration and luxury services. Ultimate choice for large-scale musical celebrations featuring premium installations and professional team.',
    features: [
      'Complete venue transformation',
      'Grand performance stage',
      'Premium lighting and effects',
      'Multiple entertainment zones',
      'Full-service decoration team',
    ],
    vendor: {
      id: 'v3',
      name: 'Celebration Masters',
      rating: 4.7,
      totalOrders: 280,
    },
    inStock: true,
  },

  // ========================================
  // WEDDING CATEGORY
  // Using YOUR uploaded images from ImgBB
  // ========================================
  {
    id: 'wedding_001',
    title: 'Royal Wedding Ceremony Decor',
    price: 29999,
    originalPrice: 42999,
    rating: 4.9,
    reviews: 234,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/6RRv2Pn9/W2.jpg',
    images: [
      'https://i.ibb.co/6RRv2Pn9/W2.jpg',
      'https://i.ibb.co/SDwZNYzD/W3.jpg',
      'https://i.ibb.co/ycyLqJxy/W4.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Wedding',
    description: 'Stunning royal wedding ceremony decoration with elegant floral arrangements and premium setup. Perfect for creating unforgettable memories with luxurious decor elements and professional installation.',
    features: [
      'Premium floral arch and mandap decoration',
      'Elegant stage setup with draped fabrics',
      'Professional lighting arrangements',
      'Customizable color themes',
      'Complete venue decoration coverage',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'wedding_002',
    title: 'Elegant Wedding Stage Setup',
    price: 34999,
    originalPrice: 49999,
    rating: 4.8,
    reviews: 298,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/XrPGPkbC/W5.jpg',
    images: [
      'https://i.ibb.co/XrPGPkbC/W5.jpg',
      'https://i.ibb.co/RZm8S3g/W6.jpg',
      'https://i.ibb.co/ksYhGz4f/W7.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Wedding',
    description: 'Grand wedding stage decoration featuring luxurious fabrics, elaborate floral designs, and sophisticated lighting. Creates a majestic atmosphere for your special day with complete professional setup.',
    features: [
      'Luxury stage backdrop design',
      'Premium seating arrangements',
      'Elaborate floral centerpieces',
      'Coordinated color schemes',
      'Professional installation team',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.8,
      totalOrders: 520,
    },
    inStock: true,
  },
  {
    id: 'wedding_003',
    title: 'Traditional Wedding Mandap',
    price: 39999,
    originalPrice: 54999,
    rating: 4.9,
    reviews: 356,
    organizer: 'Cultural Celebrations',
    image: 'https://i.ibb.co/Z1khxFfw/W8.jpg',
    images: [
      'https://i.ibb.co/Z1khxFfw/W8.jpg',
      'https://i.ibb.co/dsxnBDGD/W9.jpg',
      'https://i.ibb.co/NgFNgSbQ/W10.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 27,
    category: 'Wedding',
    description: 'Magnificent traditional mandap setup with intricate floral decorations and cultural elements. Perfect for Hindu wedding ceremonies with complete traditional arrangements and professional setup.',
    features: [
      'Traditional mandap structure',
      'Intricate floral decorations',
      'Sacred ceremony setup',
      'Decorative pillars and drapes',
      'Complete lighting arrangements',
    ],
    vendor: {
      id: 'v4',
      name: 'Cultural Celebrations',
      rating: 4.9,
      totalOrders: 380,
    },
    inStock: true,
  },
  {
    id: 'wedding_004',
    title: 'Premium Wedding Reception Decor',
    price: 44999,
    originalPrice: 64999,
    rating: 4.9,
    reviews: 412,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/Gfs9rthv/W11.jpg',
    images: [
      'https://i.ibb.co/Gfs9rthv/W11.jpg',
      'https://i.ibb.co/TMGMXtpt/W12.jpg',
      'https://i.ibb.co/V0S5p4pL/W13.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Wedding',
    description: 'Opulent wedding reception decoration with grand stage setup, premium lighting, and luxurious fabric draping. Creates an unforgettable ambiance for your wedding celebration.',
    features: [
      'Grand reception stage backdrop',
      'Premium fabric and draping',
      'Professional lighting system',
      'VIP seating arrangements',
      'Complete venue transformation',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 490,
    },
    inStock: true,
  },
  {
    id: 'wedding_005',
    title: 'Garden Wedding Ceremony Setup',
    price: 32999,
    originalPrice: 46999,
    rating: 4.8,
    reviews: 334,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/Z1L2zQ9y/W14.jpg',
    images: [
      'https://i.ibb.co/Z1L2zQ9y/W14.jpg',
      'https://i.ibb.co/Rkf9PTjc/W15.jpg',
      'https://i.ibb.co/gb4Ysvc9/W16.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Wedding',
    description: 'Beautiful garden wedding decoration with natural floral arrangements, outdoor ceremony setup, and romantic ambiance. Perfect for intimate outdoor wedding celebrations.',
    features: [
      'Garden arch with fresh flowers',
      'Outdoor seating arrangements',
      'Natural lighting setup',
      'Romantic pathway decorations',
      'Weather-proof installations',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.8,
      totalOrders: 430,
    },
    inStock: true,
  },
  {
    id: 'wedding_006',
    title: 'Luxury Wedding Complete Package',
    price: 54999,
    originalPrice: 79999,
    rating: 4.9,
    reviews: 478,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/B2jLswVM/W17.jpg',
    images: [
      'https://i.ibb.co/B2jLswVM/W17.jpg',
      'https://i.ibb.co/KcxvwmCP/W18.jpg',
      'https://i.ibb.co/RTnfstnF/W19.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Wedding',
    description: 'All-inclusive luxury wedding decoration package with complete venue transformation, premium materials, and comprehensive setup. The ultimate choice for grand wedding celebrations.',
    features: [
      'Complete venue decoration',
      'Premium quality materials',
      'Grand stage and mandap setup',
      'Professional design consultation',
      'Full-service installation team',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 560,
    },
    inStock: true,
  },

  // ========================================
  // RECEPTION CATEGORY
  // Using YOUR uploaded images from ImgBB
  // ========================================
  {
    id: 'reception_001',
    title: 'Grand Reception Stage Decor',
    price: 49999,
    originalPrice: 69999,
    rating: 4.9,
    reviews: 312,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/Zprq6Vck/R1.jpg',
    images: [
      'https://i.ibb.co/Zprq6Vck/R1.jpg',
      'https://i.ibb.co/MkSqmfg3/R2.jpg',
      'https://i.ibb.co/93rtZ4yg/R3.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 29,
    category: 'Reception',
    description: 'Magnificent reception stage decoration with premium fabrics, elaborate lighting, and luxurious setup. Creates a stunning focal point for your wedding reception with professional grand installation.',
    features: [
      'Premium stage backdrop with elegant draping',
      'Professional lighting and spotlights',
      'Luxury seating for bride and groom',
      'Elaborate floral arrangements',
      'Complete venue decoration package',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 560,
    },
    inStock: true,
  },
  {
    id: 'reception_002',
    title: 'Royal Reception Complete Setup',
    price: 54999,
    originalPrice: 79999,
    rating: 4.9,
    reviews: 398,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/q37Xr7Yz/R4.jpg',
    images: [
      'https://i.ibb.co/q37Xr7Yz/R4.jpg',
      'https://i.ibb.co/FLft0T0m/R5.jpg',
      'https://i.ibb.co/pjCHF8kr/R6.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Reception',
    description: 'Opulent royal reception decoration with complete venue transformation. Features premium stage setup, luxurious fabric work, and comprehensive lighting design for an unforgettable celebration.',
    features: [
      'Royal stage with premium backdrop',
      'Complete venue draping and decoration',
      'Professional lighting system',
      'Floral centerpieces and arrangements',
      'VIP seating area setup',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 620,
    },
    inStock: true,
  },
  {
    id: 'reception_003',
    title: 'Luxury Reception Hall Decor',
    price: 59999,
    originalPrice: 84999,
    rating: 4.8,
    reviews: 445,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/pBtZv6yZ/R7.jpg',
    images: [
      'https://i.ibb.co/pBtZv6yZ/R7.jpg',
      'https://i.ibb.co/v6HfTGMy/R8.jpg',
      'https://i.ibb.co/21kJHgYW/R9.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 29,
    category: 'Reception',
    description: 'Premium luxury reception hall decoration with sophisticated design elements. Complete venue transformation featuring elegant stage setup, premium fabrics, and professional lighting arrangements.',
    features: [
      'Luxury stage backdrop design',
      'Premium fabric draping throughout venue',
      'Advanced lighting and ambiance setup',
      'Elaborate floral decoration packages',
      'Complete reception area coverage',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.8,
      totalOrders: 580,
    },
    inStock: true,
  },
  {
    id: 'reception_004',
    title: 'Premium Reception Celebration Setup',
    price: 44999,
    originalPrice: 64999,
    rating: 4.9,
    reviews: 367,
    organizer: 'Cultural Celebrations',
    image: 'https://i.ibb.co/XvjHd8b/R10.jpg',
    images: [
      'https://i.ibb.co/XvjHd8b/R10.jpg',
      'https://i.ibb.co/hjych7j/R11.jpg',
      'https://i.ibb.co/xrbB6F7/R12.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Reception',
    description: 'Elegant reception celebration decoration with beautiful stage setup and complete venue arrangements. Perfect for creating memorable reception experiences with professional decoration services.',
    features: [
      'Elegant stage decoration',
      'Premium seating arrangements',
      'Professional lighting setup',
      'Floral centerpieces and props',
      'Complete decoration coverage',
    ],
    vendor: {
      id: 'v4',
      name: 'Cultural Celebrations',
      rating: 4.9,
      totalOrders: 490,
    },
    inStock: true,
  },
  {
    id: 'reception_005',
    title: 'Traditional Reception Decor Package',
    price: 39999,
    originalPrice: 57999,
    rating: 4.8,
    reviews: 334,
    organizer: 'Cultural Celebrations',
    image: 'https://i.ibb.co/7xNhRCHL/R13.jpg',
    images: [
      'https://i.ibb.co/7xNhRCHL/R13.jpg',
      'https://i.ibb.co/Qvd4sb4D/R14.jpg',
      'https://i.ibb.co/B27tcDC7/R15.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Reception',
    description: 'Traditional reception decoration with cultural elements and elegant setup. Features beautiful stage arrangements, traditional props, and complete venue decoration for authentic celebration.',
    features: [
      'Traditional stage decoration',
      'Cultural themed arrangements',
      'Premium fabric and draping',
      'Traditional floral designs',
      'Complete reception setup',
    ],
    vendor: {
      id: 'v4',
      name: 'Cultural Celebrations',
      rating: 4.8,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'reception_006',
    title: 'Deluxe Reception Grand Package',
    price: 64999,
    originalPrice: 92999,
    rating: 4.9,
    reviews: 478,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/Qvn1YN5Y/R16.jpg',
    images: [
      'https://i.ibb.co/Qvn1YN5Y/R16.jpg',
      'https://i.ibb.co/Hfv8bVvv/R17.jpg',
      'https://i.ibb.co/60XSdRhF/R18.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Reception',
    description: 'All-inclusive deluxe reception decoration package with premium materials and grand setup. Ultimate choice for luxury wedding receptions featuring complete venue transformation and professional services.',
    features: [
      'Grand premium stage setup',
      'Complete venue transformation',
      'Luxury fabric and lighting design',
      'Elaborate floral arrangements',
      'Full-service decoration team',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 640,
    },
    inStock: true,
  },

  // ========================================
  // ANNIVERSARY CATEGORY
  // Using YOUR uploaded images from ImgBB
  // ========================================
  {
    id: 'anniversary_001',
    title: 'Romantic Anniversary Celebration',
    price: 22999,
    originalPrice: 32999,
    rating: 4.9,
    reviews: 189,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/dsRMFFRh/A1.jpg',
    images: [
      'https://i.ibb.co/dsRMFFRh/A1.jpg',
      'https://i.ibb.co/jZfj7TMM/A2.jpg',
      'https://i.ibb.co/zhsgL8Yt/A3.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Anniversary',
    description: 'Beautiful romantic anniversary celebration decoration with elegant setup and charming ambiance. Perfect for creating memorable moments celebrating your love story with sophisticated decor elements.',
    features: [
      'Romantic lighting arrangements',
      'Elegant backdrop design',
      'Premium floral decorations',
      'Intimate seating setup',
      'Complete celebration package',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'anniversary_002',
    title: 'Elegant Anniversary Party Setup',
    price: 26999,
    originalPrice: 38999,
    rating: 4.8,
    reviews: 234,
    organizer: 'Joyful Celebrations',
    image: 'https://i.ibb.co/7JdNcd7p/A4.jpg',
    images: [
      'https://i.ibb.co/7JdNcd7p/A4.jpg',
      'https://i.ibb.co/35tMhTTx/A5.jpg',
      'https://i.ibb.co/Y448hhWm/A6.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Anniversary',
    description: 'Elegant anniversary party decoration with stylish setup and premium elements. Ideal for celebrating milestone anniversaries with beautiful arrangements and joyful atmosphere.',
    features: [
      'Stylish party decorations',
      'Premium table settings',
      'Beautiful balloon arrangements',
      'Photo booth backdrop',
      'Professional decoration service',
    ],
    vendor: {
      id: 'v2',
      name: 'Joyful Celebrations',
      rating: 4.8,
      totalOrders: 320,
    },
    inStock: true,
  },
  {
    id: 'anniversary_003',
    title: 'Premium Anniversary Dinner Decor',
    price: 29999,
    originalPrice: 42999,
    rating: 4.9,
    reviews: 267,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/mVkS8wRW/A8.jpg',
    images: [
      'https://i.ibb.co/mVkS8wRW/A8.jpg',
      'https://i.ibb.co/cSddZYFk/A9.jpg',
      'https://i.ibb.co/8DwSY9Mz/A10.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Anniversary',
    description: 'Premium anniversary dinner decoration with sophisticated ambiance and luxury elements. Perfect for intimate celebrations featuring elegant table settings and romantic lighting.',
    features: [
      'Sophisticated table decorations',
      'Luxury fabric draping',
      'Romantic candlelight setup',
      'Premium floral centerpieces',
      'Complete venue styling',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'anniversary_004',
    title: 'Grand Anniversary Function',
    price: 32999,
    originalPrice: 46999,
    rating: 4.8,
    reviews: 298,
    organizer: 'Celebration Masters',
    image: 'https://i.ibb.co/9mxrWNTR/A11.jpg',
    images: [
      'https://i.ibb.co/9mxrWNTR/A11.jpg',
      'https://i.ibb.co/CK0JtxYt/A12.jpg',
      'https://i.ibb.co/0VcQfw5M/A13.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Anniversary',
    description: 'Grand anniversary function decoration with complete setup and premium services. Ideal for large gatherings celebrating love and togetherness with comprehensive venue decoration.',
    features: [
      'Grand venue decoration',
      'Premium stage setup',
      'Professional lighting system',
      'Multiple seating arrangements',
      'Full-service decoration team',
    ],
    vendor: {
      id: 'v3',
      name: 'Celebration Masters',
      rating: 4.7,
      totalOrders: 280,
    },
    inStock: true,
  },
  {
    id: 'anniversary_005',
    title: 'Luxury Anniversary Package',
    price: 27999,
    originalPrice: 39999,
    rating: 4.9,
    reviews: 312,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/GfxZwzjN/A14.jpg',
    images: [
      'https://i.ibb.co/GfxZwzjN/A14.jpg',
      'https://i.ibb.co/N2GDVZtK/A15.jpg',
      'https://i.ibb.co/xSHx8vLM/A16.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Anniversary',
    description: 'Luxury anniversary package with exquisite decorations and elegant styling. Perfect for creating unforgettable celebration memories with premium design elements and professional execution.',
    features: [
      'Exquisite decor elements',
      'Elegant venue styling',
      'Premium balloon installations',
      'Designer table arrangements',
      'Complete celebration setup',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'anniversary_006',
    title: 'Royal Anniversary Celebration',
    price: 34999,
    originalPrice: 49999,
    rating: 4.9,
    reviews: 345,
    organizer: 'Celebration Masters',
    image: 'https://i.ibb.co/pjV1Q86n/A17.jpg',
    images: [
      'https://i.ibb.co/pjV1Q86n/A17.jpg',
      'https://i.ibb.co/Vp2Mst2x/A18.jpg',
      'https://i.ibb.co/JR30mYZm/A19.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Anniversary',
    description: 'Royal anniversary celebration with complete venue transformation and luxury services. Ultimate choice for grand milestone celebrations featuring premium installations and comprehensive decoration.',
    features: [
      'Complete venue transformation',
      'Royal stage and backdrop',
      'Premium lighting and effects',
      'Elaborate floral arrangements',
      'Full-service professional team',
    ],
    vendor: {
      id: 'v3',
      name: 'Celebration Masters',
      rating: 4.7,
      totalOrders: 280,
    },
    inStock: true,
  },

  // ========================================
  // WELCOME BABY CATEGORY
  // Using YOUR uploaded images from ImgBB
  // ========================================
  {
    id: 'welcomebaby_001',
    title: 'Adorable Welcome Baby Setup',
    price: 17999,
    originalPrice: 25999,
    rating: 4.9,
    reviews: 201,
    organizer: 'Sweet Celebrations',
    image: 'https://i.ibb.co/QjT3FJKq/WB1.jpg',
    images: [
      'https://i.ibb.co/QjT3FJKq/WB1.jpg',
      'https://i.ibb.co/8LVhS74H/WB2.jpg',
      'https://i.ibb.co/RGNMzZ8f/WB3.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Welcome Baby',
    description: 'Adorable welcome baby decoration with charming elements and sweet colors. Perfect for celebrating your newborn arrival with heartwarming decor that creates precious memories.',
    features: [
      'Charming baby-themed decor',
      'Sweet color combinations',
      'Photo-worthy backdrop',
      'Welcome signage included',
      'Complete celebration setup',
    ],
    vendor: {
      id: 'v4',
      name: 'Sweet Celebrations',
      rating: 4.8,
      totalOrders: 295,
    },
    inStock: true,
  },
  {
    id: 'welcomebaby_002',
    title: 'Sweet Baby Welcome Celebration',
    price: 20999,
    originalPrice: 29999,
    rating: 4.8,
    reviews: 189,
    organizer: 'Joyful Celebrations',
    image: 'https://i.ibb.co/hF870Gbz/WB4.jpg',
    images: [
      'https://i.ibb.co/hF870Gbz/WB4.jpg',
      'https://i.ibb.co/kVkrgYdD/WB5.jpg',
      'https://i.ibb.co/fz146SRg/WB6.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Welcome Baby',
    description: 'Sweet baby welcome celebration setup with delightful decorations. Creates a joyful atmosphere to welcome your little one with beautiful themed elements and lovely details.',
    features: [
      'Delightful themed decorations',
      'Joyful celebration atmosphere',
      'Beautiful balloon arrangements',
      'Themed props and accessories',
      'Professional styling service',
    ],
    vendor: {
      id: 'v2',
      name: 'Joyful Celebrations',
      rating: 4.8,
      totalOrders: 320,
    },
    inStock: true,
  },
  {
    id: 'welcomebaby_003',
    title: 'Elegant Welcome Baby Decor',
    price: 22999,
    originalPrice: 32999,
    rating: 4.9,
    reviews: 234,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/x8sHfyPr/WB7.jpg',
    images: [
      'https://i.ibb.co/x8sHfyPr/WB7.jpg',
      'https://i.ibb.co/BKq8wg72/WB8.jpg',
      'https://i.ibb.co/WvcQYqZn/WB9.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Welcome Baby',
    description: 'Elegant welcome baby decoration with sophisticated styling and premium elements. Ideal for creating a refined celebration welcoming your newborn with grace and beauty.',
    features: [
      'Sophisticated styling elements',
      'Premium quality decorations',
      'Elegant color palette',
      'Designer backdrop setup',
      'Complete venue decoration',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'welcomebaby_004',
    title: 'Premium Welcome Baby Package',
    price: 24999,
    originalPrice: 35999,
    rating: 4.9,
    reviews: 256,
    organizer: 'Sweet Celebrations',
    image: 'https://i.ibb.co/BH5qsmvy/WB10.jpg',
    images: [
      'https://i.ibb.co/BH5qsmvy/WB10.jpg',
      'https://i.ibb.co/TMCrkcZQ/WB11.jpg',
      'https://i.ibb.co/7xrxjVdZ/WB12.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Welcome Baby',
    description: 'Premium welcome baby package with exquisite decorations and luxury styling. Perfect for an upscale celebration featuring designer elements and meticulous attention to detail.',
    features: [
      'Luxury decoration elements',
      'Exquisite design details',
      'Premium balloon installations',
      'Designer themed props',
      'Full-service setup team',
    ],
    vendor: {
      id: 'v4',
      name: 'Sweet Celebrations',
      rating: 4.8,
      totalOrders: 295,
    },
    inStock: true,
  },
  {
    id: 'welcomebaby_005',
    title: 'Charming Baby Arrival Celebration',
    price: 21999,
    originalPrice: 31999,
    rating: 4.8,
    reviews: 218,
    organizer: 'Joyful Celebrations',
    image: 'https://i.ibb.co/Dhrv64n/WB13.jpg',
    images: [
      'https://i.ibb.co/Dhrv64n/WB13.jpg',
      'https://i.ibb.co/QjT3FJKq/WB1.jpg',
      'https://i.ibb.co/8LVhS74H/WB2.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Welcome Baby',
    description: 'Charming baby arrival celebration with heartwarming decorations. Creates a welcoming atmosphere to celebrate your newborn with joy and beautiful themed arrangements.',
    features: [
      'Heartwarming decorations',
      'Welcoming atmosphere',
      'Beautiful themed arrangements',
      'Photo opportunity setups',
      'Complete celebration package',
    ],
    vendor: {
      id: 'v2',
      name: 'Joyful Celebrations',
      rating: 4.8,
      totalOrders: 320,
    },
    inStock: true,
  },
  {
    id: 'welcomebaby_006',
    title: 'Grand Welcome Baby Celebration',
    price: 26999,
    originalPrice: 38999,
    rating: 4.9,
    reviews: 278,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/RGNMzZ8f/WB3.jpg',
    images: [
      'https://i.ibb.co/RGNMzZ8f/WB3.jpg',
      'https://i.ibb.co/hF870Gbz/WB4.jpg',
      'https://i.ibb.co/kVkrgYdD/WB5.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Welcome Baby',
    description: 'Grand welcome baby celebration with complete venue transformation. Ultimate choice for celebrating your newborn arrival featuring premium installations and professional execution.',
    features: [
      'Complete venue transformation',
      'Grand decorative installations',
      'Premium themed elements',
      'Multiple celebration zones',
      'Full-service professional team',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },

  // ========================================
  // BABY SHOWER CATEGORY
  // Using YOUR uploaded images from ImgBB
  // ========================================
  {
    id: 'babyshower_001',
    title: 'Sweet Baby Shower Celebration',
    price: 18999,
    originalPrice: 26999,
    rating: 4.8,
    reviews: 187,
    organizer: 'Sweet Celebrations',
    image: 'https://i.ibb.co/NdJ9ft1g/BS1.jpg',
    images: [
      'https://i.ibb.co/NdJ9ft1g/BS1.jpg',
      'https://i.ibb.co/Qwd79rZ/BS2.jpg',
      'https://i.ibb.co/Pz1yrxy0/BS3.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Baby Shower',
    description: 'Adorable baby shower decoration with pastel colors and cute themed elements. Perfect for celebrating the arrival of a new bundle of joy with sweet and memorable decor.',
    features: [
      'Pastel color theme decoration',
      'Cute baby-themed elements',
      'Photo booth setup',
      'Balloon arrangements',
      'Complete shower decor package',
    ],
    vendor: {
      id: 'v4',
      name: 'Sweet Celebrations',
      rating: 4.8,
      totalOrders: 295,
    },
    inStock: true,
  },
  {
    id: 'babyshower_002',
    title: 'Elegant Baby Shower Setup',
    price: 21999,
    originalPrice: 31999,
    rating: 4.9,
    reviews: 223,
    organizer: 'Joyful Celebrations',
    image: 'https://i.ibb.co/WvHNs9g8/BS4.jpg',
    images: [
      'https://i.ibb.co/WvHNs9g8/BS4.jpg',
      'https://i.ibb.co/MDW4GLL4/BS5.jpg',
      'https://i.ibb.co/hRyC5JBK/BS6.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Baby Shower',
    description: 'Elegant baby shower setup with sophisticated decor and charming details. Ideal for creating a beautiful celebration with premium styling and lovely ambiance.',
    features: [
      'Sophisticated decor styling',
      'Charming themed elements',
      'Premium balloon arrangements',
      'Dessert table decoration',
      'Professional setup service',
    ],
    vendor: {
      id: 'v2',
      name: 'Joyful Celebrations',
      rating: 4.8,
      totalOrders: 320,
    },
    inStock: true,
  },
  {
    id: 'babyshower_003',
    title: 'Delightful Baby Shower Decor',
    price: 19999,
    originalPrice: 28999,
    rating: 4.7,
    reviews: 198,
    organizer: 'Sweet Celebrations',
    image: 'https://i.ibb.co/bgbB1FVr/BS7.jpg',
    images: [
      'https://i.ibb.co/bgbB1FVr/BS7.jpg',
      'https://i.ibb.co/XkXQcntX/BS8.jpg',
      'https://i.ibb.co/273FxSqQ/BS9.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Baby Shower',
    description: 'Delightful baby shower decoration creating a warm and welcoming atmosphere. Features adorable themed decorations and comfortable space for guests to celebrate.',
    features: [
      'Warm welcoming atmosphere',
      'Adorable themed decorations',
      'Comfortable guest seating',
      'Beautiful backdrop design',
      'Complete venue decoration',
    ],
    vendor: {
      id: 'v4',
      name: 'Sweet Celebrations',
      rating: 4.8,
      totalOrders: 295,
    },
    inStock: true,
  },
  {
    id: 'babyshower_004',
    title: 'Premium Baby Shower Package',
    price: 24999,
    originalPrice: 35999,
    rating: 4.9,
    reviews: 245,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/NgkcjXtL/BS10.jpg',
    images: [
      'https://i.ibb.co/NgkcjXtL/BS10.jpg',
      'https://i.ibb.co/1J0Y1cXN/BS11.jpg',
      'https://i.ibb.co/Qjh2cVZ5/BS12.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Baby Shower',
    description: 'Premium baby shower package with exquisite decor and luxury elements. Perfect for those seeking an upscale celebration with elegant styling and attention to detail.',
    features: [
      'Luxury decor elements',
      'Exquisite styling details',
      'Premium balloon installations',
      'Designer table settings',
      'Full-service decoration team',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'babyshower_005',
    title: 'Charming Baby Welcome Setup',
    price: 22999,
    originalPrice: 32999,
    rating: 4.8,
    reviews: 212,
    organizer: 'Joyful Celebrations',
    image: 'https://i.ibb.co/1YDPVFZB/BS13.jpg',
    images: [
      'https://i.ibb.co/1YDPVFZB/BS13.jpg',
      'https://i.ibb.co/99F55vCQ/BS14.jpg',
      'https://i.ibb.co/nNs0FLTs/BS15.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Baby Shower',
    description: 'Charming baby welcome setup with delightful decorations and joyful ambiance. Excellent choice for celebrating the upcoming arrival with style and sweetness.',
    features: [
      'Delightful themed decorations',
      'Joyful color schemes',
      'Creative balloon designs',
      'Welcome signage and props',
      'Complete celebration package',
    ],
    vendor: {
      id: 'v2',
      name: 'Joyful Celebrations',
      rating: 4.8,
      totalOrders: 320,
    },
    inStock: true,
  },
  {
    id: 'babyshower_006',
    title: 'Grand Baby Shower Celebration',
    price: 26999,
    originalPrice: 38999,
    rating: 4.9,
    reviews: 267,
    organizer: 'Sweet Celebrations',
    image: 'https://i.ibb.co/hRBB5K20/BS16.jpg',
    images: [
      'https://i.ibb.co/hRBB5K20/BS16.jpg',
      'https://i.ibb.co/9mZ9rmhN/BS17.jpg',
      'https://i.ibb.co/NdJ9ft1g/BS1.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Baby Shower',
    description: 'Grand baby shower celebration package with complete venue transformation. Ultimate choice for an unforgettable celebration featuring premium decorations and professional execution.',
    features: [
      'Complete venue transformation',
      'Grand decorative installations',
      'Premium themed elements',
      'Multiple photo zones',
      'Full-service professional team',
    ],
    vendor: {
      id: 'v4',
      name: 'Sweet Celebrations',
      rating: 4.8,
      totalOrders: 295,
    },
    inStock: true,
  },

  // ========================================
  // BIRTHDAY CATEGORY
  // Using YOUR uploaded images from ImgBB
  // ========================================
  {
    id: 'birthday_001',
    title: 'Colorful Birthday Party Setup',
    price: 16999,
    originalPrice: 24999,
    rating: 4.9,
    reviews: 234,
    organizer: 'Joyful Celebrations',
    image: 'https://i.ibb.co/qFcyCvZJ/B1.jpg',
    images: [
      'https://i.ibb.co/qFcyCvZJ/B1.jpg',
      'https://i.ibb.co/ksc1cxcN/B2.jpg',
      'https://i.ibb.co/6RqG9SmS/B3.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 32,
    category: 'Birthday',
    description: 'Vibrant and colorful birthday party decoration with fun balloons and festive elements. Perfect for creating joyful celebrations filled with energy and excitement for all ages.',
    features: [
      'Colorful balloon arrangements',
      'Festive party decorations',
      'Fun themed elements',
      'Photo booth backdrop',
      'Complete party setup',
    ],
    vendor: {
      id: 'v2',
      name: 'Joyful Celebrations',
      rating: 4.8,
      totalOrders: 320,
    },
    inStock: true,
  },
  {
    id: 'birthday_002',
    title: 'Elegant Birthday Celebration',
    price: 19999,
    originalPrice: 28999,
    rating: 4.8,
    reviews: 198,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/RTfWhKvb/B4.jpg',
    images: [
      'https://i.ibb.co/RTfWhKvb/B4.jpg',
      'https://i.ibb.co/tMsSZ2TN/B5.jpg',
      'https://i.ibb.co/BKH10LMS/B6.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Birthday',
    description: 'Elegant birthday celebration setup with sophisticated styling and premium decorations. Ideal for memorable milestone birthdays with refined aesthetic and beautiful details.',
    features: [
      'Sophisticated decor styling',
      'Premium balloon designs',
      'Elegant table settings',
      'Themed backdrop setup',
      'Professional decoration service',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'birthday_003',
    title: 'Kids Birthday Party Package',
    price: 14999,
    originalPrice: 21999,
    rating: 4.9,
    reviews: 267,
    organizer: 'Sweet Celebrations',
    image: 'https://i.ibb.co/9k8dZ42T/B7.jpg',
    images: [
      'https://i.ibb.co/9k8dZ42T/B7.jpg',
      'https://i.ibb.co/KzQhKjDR/B8.jpg',
      'https://i.ibb.co/B5pLnNhX/B9.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 32,
    category: 'Birthday',
    description: 'Fun and exciting kids birthday party decoration with playful themes and engaging elements. Perfect for creating magical celebrations that children will remember forever.',
    features: [
      'Kid-friendly themed decor',
      'Playful balloon installations',
      'Interactive party elements',
      'Fun photo opportunities',
      'Age-appropriate decorations',
    ],
    vendor: {
      id: 'v4',
      name: 'Sweet Celebrations',
      rating: 4.8,
      totalOrders: 295,
    },
    inStock: true,
  },
  {
    id: 'birthday_004',
    title: 'Premium Birthday Function Decor',
    price: 22999,
    originalPrice: 32999,
    rating: 4.9,
    reviews: 312,
    organizer: 'Elite Events Co.',
    image: 'https://i.ibb.co/VWhdZF5B/B11.jpg',
    images: [
      'https://i.ibb.co/VWhdZF5B/B11.jpg',
      'https://i.ibb.co/zWpsWqtT/B12.jpg',
      'https://i.ibb.co/gFRVwD4J/B13.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 30,
    category: 'Birthday',
    description: 'Premium birthday function decoration with luxurious setup and exquisite design elements. Features elegant styling perfect for upscale birthday celebrations and special milestones.',
    features: [
      'Luxury decoration elements',
      'Premium venue styling',
      'Sophisticated lighting setup',
      'Designer party props',
      'Complete function coverage',
    ],
    vendor: {
      id: 'v1',
      name: 'Elite Events Co.',
      rating: 4.9,
      totalOrders: 450,
    },
    inStock: true,
  },
  {
    id: 'birthday_005',
    title: 'Themed Birthday Party Setup',
    price: 18999,
    originalPrice: 27999,
    rating: 4.8,
    reviews: 245,
    organizer: 'Joyful Celebrations',
    image: 'https://i.ibb.co/m5bsFv9t/B14.jpg',
    images: [
      'https://i.ibb.co/m5bsFv9t/B14.jpg',
      'https://i.ibb.co/8qBWqCw/B15.jpg',
      'https://i.ibb.co/xKhG66Bt/B16.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 32,
    category: 'Birthday',
    description: 'Creative themed birthday party decoration with customizable designs and unique elements. Perfect for bringing your birthday party vision to life with personalized styling.',
    features: [
      'Customizable theme decorations',
      'Creative design elements',
      'Themed balloon arrangements',
      'Personalized party props',
      'Professional setup team',
    ],
    vendor: {
      id: 'v2',
      name: 'Joyful Celebrations',
      rating: 4.8,
      totalOrders: 320,
    },
    inStock: true,
  },
  {
    id: 'birthday_006',
    title: 'Grand Birthday Celebration Package',
    price: 24999,
    originalPrice: 35999,
    rating: 4.9,
    reviews: 289,
    organizer: 'Celebration Masters',
    image: 'https://i.ibb.co/zVyYq3DZ/B17.jpg',
    images: [
      'https://i.ibb.co/zVyYq3DZ/B17.jpg',
      'https://i.ibb.co/HTbhFxyY/B18.jpg',
      'https://i.ibb.co/zh3BtcjH/B19.jpg',
    ],
    modelUrl: MODEL_BASE_URL + 'Astronaut.glb',
    discount: 31,
    category: 'Birthday',
    description: 'Grand birthday celebration package with complete venue transformation and premium services. Ultimate choice for large-scale birthday parties featuring spectacular installations and professional execution.',
    features: [
      'Complete venue transformation',
      'Grand decorative installations',
      'Premium party elements',
      'Multiple celebration zones',
      'Full-service professional team',
    ],
    vendor: {
      id: 'v3',
      name: 'Celebration Masters',
      rating: 4.7,
      totalOrders: 280,
    },
    inStock: true,
  },
];

export type DecorProduct = typeof DECOR_PRODUCTS[0];
